### ISSUE TITLE
支持多版本Redis client

### ISSUE THREAD

**Issue by harryeti** [jefferyjob/go-redislock#12]
能否支持多版本的github.com/redis/go-redis，v8和v9

**Comment by jefferyjob** [comment]
我看一下

**Comment by jefferyjob** [comment]
已经兼容了 v8 和 v9， 您可以试用，如果使用过程中有其他问题，可以及时与我联络

**Comment by jefferyjob** [comment]
v8 和 v9 的地址不一样

```
github.com/go-redis/redis/v8
github.com/redis/go-redis/v9
```

v9 以后被官方收录，所以兼容起来有点困难

<img width="1086" alt="image" src="https://github.com/jefferyjob/go-redislock/assets/24731115/0583828c-df7f-4e47-80d4-5e4bab126996">

**Comment by harryeti** [comment]
似乎是有些困难，也没法提取一个公用的模型或者接口来处理这个兼容的事情。

**Comment by jefferyjob** [comment]
倒是可以，主要是这两个仓库地址不一样。如果仓库地址是一致的，通过定义接口的方式是可以实现的

**Comment by yann0917** [comment]
支持 v6 版本吗？

**Comment by jefferyjob** [comment]
> 支持 v6 版本吗？

暂时不支持，如果后续支持了，我和您说一声
