### ISSUE TITLE
[Question]: 创建redis lock对象时报错

### ISSUE THREAD

**Issue by ZENBruce** [jefferyjob/go-redislock#36]
### Question Description

您好，在创建redis lock对象时报错：redisClient类型不符，lock := redislock.New(ctx, redisClient, "test_key")
报错内容：
Cannot use 'redisClient' (type *Client) as the type RedisInter Type does not implement 'RedisInter' as some methods are missing: EvalRO(ctx context.Context, script string, keys []string, args ...interface{}) *Cmd
EvalShaRO(ctx context.Context, sha1 string, keys []string, args ...interface{}) *Cmd
![redis](https://github.com/user-attachments/assets/e58eee8a-9cda-4a20-b9a3-32fd7e134891)
请帮忙看下，谢谢

### Relevant code or configuration

报错内容：
Cannot use 'redisClient' (type *Client) as the type RedisInter Type does not implement 'RedisInter' as some methods are missing: EvalRO(ctx context.Context, script string, keys []string, args ...interface{}) *Cmd
EvalShaRO(ctx context.Context, sha1 string, keys []string, args ...interface{}) *Cmd

**Comment by jefferyjob** [comment]
你应该使用 github.com/redis/go-redis/v9 版本

v8 和 v9 的地址不一样
github.com/go-redis/redis/v8
github.com/redis/go-redis/v9
v9 以后被官方收录

所以这里用的官方版本
